name: fhlcreative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060709'
    - '#313234'
    - '#b1b1b2'
    - '#5c5c5e'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
