name: fhlcreative
favicon: null
layout_spectrum: 0.5374691865872592
typography_spectrum: 0.2768834449816495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4086632125545293
  lightness: 0.5376247244421393
  saturation: 0.9147478060331196
  rhythmicContrast: 0.0822014887817204
purpose: []
